[project]
name = "mini-pipeline"
version = "0.1.0"
requires-python = ">=3.11"

[tool.ruff]
line-length = 110
target-version = "py311"

[tool.ruff.lint]
select = ["E", "F", "I", "UP"]

[tool.ruff.format]
quote-style = 'double'
indent-style = 'space'

[tool.pytest.ini_options]
testpaths = ["test"]
pythonpath = ["."]